### PR TITLE
Part 3: Routes and Controllers

### PR DESCRIPTION
**Pull request by hiepn-1339**
ready

Part 3: Routes and Controllers

### CODE REVIEW

**Comment by hiepn-1339** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merge pull em nhé

**Comment by hiepn-1339** [comment]
Eslint:

Screenshot from 2024-04-15 11-21-21

**Comment by hiepn-1339** [comment]
ready

**Comment by huongnt-2545** [comment]
merged

**Pull request merged**
